In [2]:
pip install yfinance

Collecting pandas-market-calendars
  Downloading pandas_market_calendars-4.6.1-py3-none-any.whl (122 kB)
Requirement already satisfied: python-dateutil in c:\users\jain2\appdata\local\programs\python\python39\lib\site-packages (from pandas-market-calendars) (2.8.2)
Requirement already satisfied: pytz in c:\users\jain2\appdata\local\programs\python\python39\lib\site-packages (from pandas-market-calendars) (2024.2)
Requirement already satisfied: pandas>=1.1 in c:\users\jain2\appdata\local\programs\python\python39\lib\site-packages (from pandas-market-calendars) (1.3.3)
Collecting exchange-calendars>=3.3
  Downloading exchange_calendars-4.5.6-py3-none-any.whl (196 kB)
Collecting pandas>=1.1
  Downloading pandas-2.2.3-cp39-cp39-win_amd64.whl (11.6 MB)
Requirement already satisfied: toolz in c:\users\jain2\appdata\local\programs\python\python39\lib\site-packages (from exchange-calendars>=3.3->pandas-market-calendars) (0.12.1)
Collecting korean-lunar-calendar
  Downloading korean_lunar_calendar-0.3.1-py3-none-any.whl (9.0 kB)
Collecting pyluach
  Downloading pyluach-2.2.0-py3-none-any.whl (25 kB)
Collecting tzdata
  Downloading tzdata-2025.1-py2.py3-none-any.whl (346 kB)
Requirement already satisfied: numpy in c:\users\jain2\appdata\local\programs\python\python39\lib\site-packages (from exchange-calendars>=3.3->pandas-market-calendars) (1.22.4)
Requirement already satisfied: six>=1.5 in c:\users\jain2\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil->pandas-market-calendars) (1.16.0)
Installing collected packages: tzdata, pyluach, pandas, korean-lunar-calendar, exchange-calendars, pandas-market-calendars
  Attempting uninstall: pandas
    Found existing installation: pandas 1.3.3
    Uninstalling pandas-1.3.3:
      Successfully uninstalled pandas-1.3.3
Successfully installed exchange-calendars-4.5.6 korean-lunar-calendar-0.3.1 pandas-2.2.3 pandas-market-calendars-4.6.1 pyluach-2.2.0 tzdata-2025.1
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 24.3.1 is available.
You should consider upgrading via the 'c:\Users\jain2\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [8]:
import yfinance as yf

ticker_symbol = "AAPL"
ticker = yf.Ticker(ticker_symbol)

historical_data = ticker.history(period="1y")

historical_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-01-08 00:00:00-05:00,181.202281,184.695178,180.615161,184.655365,59144500,0.0,0.0
2024-01-09 00:00:00-05:00,183.023358,184.247357,181.839157,184.237411,42841800,0.0,0.0
2024-01-10 00:00:00-05:00,183.451277,185.491271,183.023365,185.282303,46792900,0.0,0.0
2024-01-11 00:00:00-05:00,185.630577,186.138100,182.724814,184.685211,49128400,0.0,0.0
2024-01-12 00:00:00-05:00,185.152912,185.829605,184.287159,185.013596,40444700,0.0,0.0
...,...,...,...,...,...,...,...
2024-12-31 00:00:00-05:00,252.440002,253.279999,249.429993,250.419998,39480700,0.0,0.0
2025-01-02 00:00:00-05:00,248.929993,249.100006,241.820007,243.850006,55740700,0.0,0.0
2025-01-03 00:00:00-05:00,243.360001,244.179993,241.889999,243.360001,40244100,0.0,0.0
2025-01-06 00:00:00-05:00,244.309998,247.330002,243.199997,245.000000,45045600,0.0,0.0
2025-01-07 00:00:00-05:00,242.979996,245.550003,241.360001,242.100006,25262133,0.0,0.0

In [9]:
financials = ticker.financials
financials

,2024-09-30,2023-09-30,2022-09-30,2021-09-30,2020-09-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,NaN
Tax Rate For Calcs,0.240912,0.147192,0.162,0.133,NaN
Normalized EBITDA,134661000000.0,125820000000.0,130541000000.0,123136000000.0,NaN
Net Income From Continuing Operation Net Minority Interest,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Reconciled Depreciation,11445000000.0,11519000000.0,11104000000.0,11284000000.0,NaN
Reconciled Cost Of Revenue,210352000000.0,214137000000.0,223546000000.0,212981000000.0,NaN
EBITDA,134661000000.0,125820000000.0,130541000000.0,123136000000.0,NaN
EBIT,123216000000.0,114301000000.0,119437000000.0,111852000000.0,NaN
Net Interest Income,NaN,-183000000.0,-106000000.0,198000000.0,890000000.0
Interest Expense,NaN,3933000000.0,2931000000.0,2645000000.0,2873000000.0
Interest Income,NaN,3750000000.0,2825000000.0,2843000000.0,3763000000.0
Normalized Income,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income From Continuing And Discontinued Operation,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Total Expenses,267819000000.0,268984000000.0,274891000000.0,256868000000.0,NaN
Total Operating Income As Reported,123216000000.0,114301000000.0,119437000000.0,108949000000.0,NaN
Diluted Average Shares,NaN,15812547000.0,16325819000.0,16864919000.0,17528214000.0
Basic Average Shares,NaN,15744231000.0,16215963000.0,16701272000.0,17352119000.0
Diluted EPS,NaN,6.13,6.11,5.61,3.28
Basic EPS,NaN,6.16,6.15,5.67,3.31
Diluted NI Availto Com Stockholders,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income Common Stockholders,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income Including Noncontrolling Interests,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income Continuous Operations,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Tax Provision,29749000000.0,16741000000.0,19300000000.0,14527000000.0,NaN
Pretax Income,123485000000.0,113736000000.0,119103000000.0,109207000000.0,NaN
Other Income Expense,269000000.0,-565000000.0,-334000000.0,60000000.0,NaN
Other Non Operating Income Expenses,269000000.0,-565000000.0,-334000000.0,60000000.0,NaN
Net Non Operating Interest Income Expense,NaN,-183000000.0,-106000000.0,198000000.0,890000000.0
Interest Expense Non Operating,NaN,3933000000.0,2931000000.0,2645000000.0,2873000000.0
Interest Income Non Operating,NaN,3750000000.0,2825000000.0,2843000000.0,3763000000.0
Operating Income,123216000000.0,114301000000.0,119437000000.0,108949000000.0,NaN
Operating Expense,57467000000.0,54847000000.0,51345000000.0,43887000000.0,NaN
Research And Development,31370000000.0,29915000000.0,26251000000.0,21914000000.0,NaN
Selling General And Administration,26097000000.0,24932000000.0,25094000000.0,21973000000.0,NaN
Gross Profit,180683000000.0,169148000000.0,170782000000.0,152836000000.0,NaN
Cost Of Revenue,210352000000.0,214137000000.0,223546000000.0,212981000000.0,NaN
Total Revenue,391035000000.0,383285000000.0,394328000000.0,365817000000.0,NaN
Operating Revenue,391035000000.0,383285000000.0,394328000000.0,365817000000.0,NaN

In [10]:
actions = ticker.actions
actions

                           Dividends  Stock Splits
Date
2024-02-09 00:00:00-05:00       0.24           0.0
2024-05-10 00:00:00-04:00       0.25           0.0
2024-08-12 00:00:00-04:00       0.25           0.0
2024-11-08 00:00:00-05:00       0.25           0.0

In [13]:
def prime(n):
	if n<2:
		return False
	for i in range(2,n):
		if n%i==0:
			return False
	return True
		
primes = []
n = 100
for i in range(2,n):
	if prime(i):
		primes.append(i)
print(primes)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]